// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxOzGjl1DRRAXZslP7EBdD88HQH26Ea6M',
    appId: '1:581563357515:web:8ea02aac9e4b03f1c770ce',
    messagingSenderId: '581563357515',
    projectId: 'qliqcare-b9670',
    authDomain: 'qliqcare-b9670.firebaseapp.com',
    storageBucket: 'qliqcare-b9670.firebasestorage.app',
    measurementId: 'G-Y99899RD58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZVzyz0stAgng9L8iuaMqJQ3lpq21Izr8',
    appId: '1:581563357515:android:a8e508d861437eabc770ce',
    messagingSenderId: '581563357515',
    projectId: 'qliqcare-b9670',
    storageBucket: 'qliqcare-b9670.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwv9g-P9f0pv6fcxaG3U0PWh5jVEd4tug',
    appId: '1:581563357515:ios:206327719e0b58e5c770ce',
    messagingSenderId: '581563357515',
    projectId: 'qliqcare-b9670',
    storageBucket: 'qliqcare-b9670.firebasestorage.app',
    iosBundleId: 'com.caretaker.qlickcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwv9g-P9f0pv6fcxaG3U0PWh5jVEd4tug',
    appId: '1:581563357515:ios:206327719e0b58e5c770ce',
    messagingSenderId: '581563357515',
    projectId: 'qliqcare-b9670',
    storageBucket: 'qliqcare-b9670.firebasestorage.app',
    iosBundleId: 'com.caretaker.qlickcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxOzGjl1DRRAXZslP7EBdD88HQH26Ea6M',
    appId: '1:581563357515:web:3b038d1033a515a4c770ce',
    messagingSenderId: '581563357515',
    projectId: 'qliqcare-b9670',
    authDomain: 'qliqcare-b9670.firebaseapp.com',
    storageBucket: 'qliqcare-b9670.firebasestorage.app',
    measurementId: 'G-1FK7VV9Y57',
  );
}